name: interval_reminder
description: "A Flutter application that allows users to create tasks and receive reminders at scheduled repeating intervals."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local key-value storage for persistence
  shared_preferences: ^2.3.2

  # Cupertino icons for iOS style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package provides recommended lints to encourage good coding practices.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
